### ISSUE TITLE
Trained weights

### ISSUE THREAD

**Issue by BruceChen034020** [ImagingLab/Colorizing-with-GANs#1]
@ImagingLab
Can you please upload the trained weight hdf5 file?
(such as weights_cifar10_lab_dis.hdf5 etc.)

It takes too much time to train the model for me.

Thank you.

**Comment by KamyarNazeri** [comment]
@BruceChen034020 You can find the pre-trained [weights here](https://bit.ly/2JRLgyw)

We are migrating the source code to Tensorflow 1.7. Stay tuned as we'll upload the weights once the codebase is complete!

**Comment by ZoloLongZhuo** [comment]
Hello,  I am looking for how to use the hdf5  model to generate the pics with gan...Could u send the major code ?

**Comment by KamyarNazeri** [comment]
@ZoloLongZhuo The hdf5 weights are for the initial prototype code written in Keras. We'll be posting the pre-trained weights for Tensorflow shortly.

**Comment by KamyarNazeri** [comment]
@ZoloLongZhuo 
We are not suggesting the old Keras prototype. However, you can access it under the "old" branch:
https://github.com/ImagingLab/Colorizing-with-GANs/tree/old
