### ISSUE TITLE
Weights of Neural Net in DeepLearnJS Format

### ISSUE THREAD

**Issue by GlebSBrykin** [ImagingLab/Colorizing-with-GANs#11]
Can You save the weight in the format ckpt?

**Comment by knazeri** [comment]
@PABCSoft You can use the provided checkpoints to load the model in training model, and then create a tensorflow SavedModel, for example, use [simple_save](https://www.tensorflow.org/guide/saved_model#simple_save), to save the computation graph. 
Once you have the SavedModel, you can use [`tensorflowjs_converter`](https://github.com/tensorflow/tfjs-converter) utility to convert it between different formats.

Having said that, I have provided a simple SavedModel and the weights in tensorflowjs format for [Places365 dataset](https://drive.google.com/drive/folders/13moTxxef1o-4Bs2YwZ6G9oLVE00ZfwXo) online. The input and output nodes for the provided weights are `input_gray` and `output` respectively.

**Comment by PABCSoft** [comment]
Hello, @knazeri, thank you for the answer. I managed to convert the weights. Now I'm trying to implement the C# version of your neural network.
