### ISSUE TITLE
Training the generator twice as much

### ISSUE THREAD

**Issue by karoly-hars** [ImagingLab/Colorizing-with-GANs#16]
I noticed in your code that you are training the generator twice in every train step and the discriminator just once (I think). 
If this is the case, did you achieve a noticeable improvement by training in this manner compared to training both networks once?

**Comment by knazeri** [comment]
@karoly-hars The problem we were trying to address was that the discriminator is learning much faster than the generator. At the time, the only solution was to either slow than the discriminator's learning rate or train generator twice as much. It does not necessarily improve the result, but rather stabilize the training!

However, I suggest the following recent papers for both stability and improvement:
- [Spectral Normalization for Generative Adversarial Networks](https://arxiv.org/abs/1802.05957)
- [Self-Attention Generative Adversarial Networks](https://arxiv.org/abs/1805.08318)
- [Geometric GAN](https://arxiv.org/abs/1705.02894)

**Comment by karoly-hars** [comment]
Thanks for the clarification. I am already experimenting with spectral norm with promising results.
