### ISSUE TITLE
Output of the discriminator is not 1-D

### ISSUE THREAD

**Issue by JannisBush** [ImagingLab/Colorizing-with-GANs#17]
Hey,

In the README it is written that the last layer of the discriminator maps the output to a scalar.
So the output shape of the discriminator should be (?,1,1,1) or (?,1), but in fact it is (?,4,4,1).

Is this intended? 

To see this, add `self.dis_real = dis_real` in line 199 and print(self.sess.run(self.dis_real, feed_dict=feed_dic).shape) in line 55 of `models.py`.
An easy fix for this problem, would be to use the `padding="VALID"` for the last layer of the discriminator. 

Best regards,
Jannis

**Comment by knazeri** [comment]
@JannisBush This was intended! We have to update the readme!
This class of discriminators is known as PatchGAN. The output of the discriminator is a `4x4` matrix with each index corresponding an image patch in the input. The receptive field of the network is `70x70` which means our discriminator evaluates `70x70` overlapping patches of the input image! 

Philip Isola has a good explanation for this: https://github.com/junyanz/pytorch-CycleGAN-and-pix2pix/issues/39#issuecomment-305575964

> This is all mathematically equivalent to if we had manually chopped up the image into 70x70 overlapping patches, run a regular discriminator over each patch, and averaged the results.

**Comment by JannisBush** [comment]
@knazeri Thanks for your clarification.
