### ISSUE TITLE
models.test issue

### ISSUE THREAD

**Issue by TonyZhang1002** [ImagingLab/Colorizing-with-GANs#19]
In your test() method in models.py, you pass one image into the model each time, in a shape of (1, 256, 256, 1), which in my experiments, create bad results.

I change the codes a little bit, put 8 or 16 images together in the shape of (8 or 16, 256, 256, 1 or 3), as you did in sample(). And then pass this into the model. This can create better results in my experiments.

Please check if that is correct.

**Comment by knazeri** [comment]
@TonyZhang1002
This might be due to batch normalization module, we need to turn the unit off at inference, otherwise, it will create bad results when testing on one image! I'll double check the code. Thanks for pointing that out.

**Comment by Chansi** [comment]
@TonyZhang1002  Did it work?
