### ISSUE TITLE
Run on custom set of images

### ISSUE THREAD

**Issue by Ruffi** [ImagingLab/Colorizing-with-GANs#4]
First, thanks for sharing your work, it's very interesting

I'm trying to run the pre-trained models on my own set of images (not using an existing dataset), what would be the proper way to do that?

**Comment by knazeri** [comment]
@Ruffi 
Basically, you can start by changing the [load method](https://github.com/ImagingLab/Colorizing-with-GANs/blob/5d668e26a8b2b3839310b6111b2fd06d7e076ed7/src/dataset.py#L113) of the `Places365Dataset` class. 
You can also create your own dataset class by inheriting from `BaseDataset`. The only method you are required to implement is the `load method`. In this case, you need to change the model's [create_dataset](https://github.com/ImagingLab/Colorizing-with-GANs/blob/5d668e26a8b2b3839310b6111b2fd06d7e076ed7/src/models.py#L349) method with your own dataset class.
As a side note, although the model is fully convolutional and you can use images of any arbitrary size at test time, the Places365 model model works best when the input size is 256x256 image!

**Comment by Ruffi** [comment]
Thanks, I'll try that :)

**Comment by adityajain28** [comment]
Hi
How were you able to run on your set of images?

**Comment by knazeri** [comment]
@adityajain28 We are planning to add a helper method so that one can easily run the model on their set of images. However, right now your best bet is to create your own dataset class as I mentioned above.

**Comment by knazeri** [comment]
Right now, if you run the tests, the images are being displayed to you and you can save them manually, however as I mentioned earlier, I'm going to add a helper method to test on custom images and save the results on disk.

**Comment by adityajain28** [comment]
The problem I am facing is not being able to run test-turing.py
It just shows loading model and it stops. Nothing happens after that.

So to visualize the images I have to run Python test-turing.py, correct? Or
is there any other method?

**Comment by knazeri** [comment]
Not sure why it might stop after loading! Right now to visualize, that's your best bet. You can change the code to do the visualization as you like. However, next week I'm adding a helper method to test the model on custom images.
