### ISSUE TITLE
no train no test

### ISSUE THREAD

**Issue by rafariva** [ImagingLab/Colorizing-with-GANs#6]
hi, i am trying to do the traing or the test, but no success. i had clone de repo and download all image and even your pretrain network.

error if try to run train.py
![image](https://user-images.githubusercontent.com/26292862/47229343-20445a00-d38d-11e8-80c6-09978a7907ef.png)

error if try to run test-eval.py
![image](https://user-images.githubusercontent.com/26292862/47229379-3baf6500-d38d-11e8-8160-27594957c8fd.png)

**Comment by knazeri** [comment]
@rafariva Judging by your error messages, it looks like you are using _pickle_ to extract cifar10 dataset inside the data loader! You can extract the dataset before and copy in the _datasets_ folder as a preprocessing step. Also it looks like you don't have the permission to read/write on the disk!

**Comment by rafariva** [comment]
pickle is what is used on the .py code. I do have RW permission. i will try manually extracttion

**Comment by rafariva** [comment]
thanks.. problem solve.
