### ISSUE TITLE
Test single image

### ISSUE THREAD

**Issue by rafariva** [ImagingLab/Colorizing-with-GANs#7]
if  have a gray image, How i can colorize a single image?

**Comment by knazeri** [comment]
We don't have a specific method to colorize one single image. At this point, you can copy them inside the validation folder and run the Turing-test to visualize them. You can easily add a method to do the job given the pre-trained weights and the source code.

**Comment by knazeri** [comment]
@rafariva  We have implemented a test procedure to evaluate the model on custom image(s)
https://github.com/ImagingLab/Colorizing-with-GANs#test
