### ISSUE TITLE
Saving Model

### ISSUE THREAD

**Issue by adityajain28** [ImagingLab/Colorizing-with-GANs#9]
Hi
I wanted to know how to save the model when we train the model with different parameters.
I am retraining the model with different parameters, and be able to save them and I am not being able to understand how to do so. 
Any help will be highly appreciated.

**Comment by knazeri** [comment]
@adityajain28 We have a [save ](https://github.com/ImagingLab/Colorizing-with-GANs/blob/5d668e26a8b2b3839310b6111b2fd06d7e076ed7/src/models.py#L233)method in models.py which you can call. In our implementation, we call this method based on the `save-interval` flag passed as input as you can see [here](https://github.com/ImagingLab/Colorizing-with-GANs/blob/5d668e26a8b2b3839310b6111b2fd06d7e076ed7/src/models.py#L90).

**Comment by adityajain28** [comment]
Thanks. The model is saving now. Just need to know how to use the model to test on images? as in color B/W images and save them?

**Comment by adityajain28** [comment]
What I mean is how to run my model on a new set of images? as in create a new dataset of images and run the model I train on it, and get color images, and save them to compare it to the original.

**Comment by knazeri** [comment]
In order to train/test on a new dataset, you either need to implement your own dataset class (similar to what we have for Places635 and Cifar10) or you can just edit those classes such that it returns your set of images. Having said that, I'm going to add a helper method to test on custom images and save the results on disk.

**Comment by adityajain28** [comment]
Thanks a lot

**Comment by knazeri** [comment]
We have implemented a test procedure to evaluate the model on custom image(s)
https://github.com/ImagingLab/Colorizing-with-GANs#test
